# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React-testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      working-directory: ./elena-frontend
      run: npm install

    - name: install jest-dom
      working-directory: ./elena-frontend
      run: yarn add -D @testing-library/jest-dom
  
    - name: run tests
      working-directory: ./elena-frontend
      run: npm test
